# Nom application
spring.application.name=marketplace-backend


# ===============================
# PostgreSQL Database
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5432/marketplace_db

spring.datasource.username=marketplace_user

spring.datasource.password=marketplacepasswd


# ===============================
# JPA / Hibernate
# ===============================

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true